name: Automated tests and static code analyzers

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/" #release branches
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  unit-tests:
    name: Phpstan, Phpcs, Phpunit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.1'

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "7.1"
          php_extensions: gmp
          version: 2.2

      - name: Run static code analyzers
        run: |
          ./vendor/bin/phpstan analyse
          ./vendor/bin/phpcs
          ./vendor/bin/security-checker security:check

      - name: Run test suite
        run: |
          php vendor/bin/phpunit
